### PR TITLE
Replace sql type text by longtext for profile field in PdoRepository

### PR DESCRIPTION
**Pull request by mkeromen**
- Fix to avoid truncated data with `XHGui\Saver\PdoSaver`

### CODE REVIEW

**Comment by glensc** [comment]
```
1) XHGui\Test\Controller\RunTest::testIndexEmpty
PDOException: SQLSTATE[42704]: Undefined object: 7 ERROR:  type "longtext" does not exist
LINE 4:               "profile"          LONGTEXT       NOT NULL,
```

looks like this is database dependent, so far we've avoided abstracting database type:
- https://github.com/perftools/xhgui/pull/332

**Comment by glensc** [comment]
I've added the driver name to the repository class:
- https://github.com/perftools/xhgui/pull/438

so this could be evaluated to make driver-specific changes

**Comment by glensc** [comment]
Rebased and changed target branch, so pay attention to update your local branch first if you add more commits to this branch

**Comment by glensc** [comment]
@mkeromen close, since you're no longer interested in this?

**Comment by Charl13** [comment]
@glensc This is actually rather important since `json_decode()` silently returns `null` on truncated data. That means no error and empty results in the callgraph. Harder to debug.

**Comment by glensc** [comment]
Closing, as seems the original author is not interested in finishing this.

**Comment by Charl13** [comment]
@glensc What about my comment? Do you want me to open a new pull request?

**Comment by glensc** [comment]
@Charl13 up to you

**Comment by Charl13** [comment]
https://github.com/perftools/xhgui/pull/474 🙏🏽

**Pull request closed without merging**
