### PR TITLE
Update Slim to 3.12.3

### LINKED ISSUE #278: When I update PHP to 7.4. Slim reports an error.
image

### PR DESCRIPTION
**Pull request by glensc**
Docs:
- Upgrade Guide: https://www.slimframework.com/docs/v3/start/upgrade.html
- Views: https://www.slimframework.com/docs/v3/features/templates.html

Fixes https://github.com/perftools/xhgui/issues/278

### CODE REVIEW

**Comment by glensc** [comment]
Seems to me it's perhaps easier to start with a slim skeleton:
- https://github.com/slimphp/Slim-Skeleton/tree/3.1.8

and transfer logic to new locations

**Comment by glensc** [comment]
slim/views have no v3 support:
- https://github.com/slimphp/Slim-Views/issues/49

**Comment by glensc** [comment]
Or port to Symfony5:
- https://github.com/composer/getcomposer.org/pull/165

**Comment by glensc** [comment]
Seems [slim/views](https://github.com/slimphp/Slim-Views) replacement is [slim/twig-view](https://github.com/slimphp/Twig-View):
- https://www.slimframework.com/docs/v3/features/templates.html

**Comment by glensc** [comment]
The v2 code mocked POST data by overwriting $_POST:
- https://github.com/perftools/xhgui/blob/776b59d4102653b794781d12408685a14d95a5c7/tests/Controller/WatchTest.php#L32

This is very different in v3:
- https://glenneggleton.com/page/slim-unit-testing
- https://stackoverflow.com/questions/40867377/mock-slim-endpoint-post-requests-with-phpunit

**Comment by glensc** [comment]
Flash messages have new package:
- https://www.slimframework.com/docs/v3/features/flash.html

**Comment by glensc** [comment]
https://github.com/slimphp/Slim-Flash#using-with-twig-view
>  If you use Twig-View, then slim-twig-flash may be a useful integration package:

- https://github.com/kanellov/slim-twig-flash

**Comment by glensc** [comment]
Revert unintended close:
- https://github.com/perftools/xhgui/pull/415#issuecomment-778168929

**Comment by tomjn** [comment]
What still needs to happen on this PR for merging? Is there a list of tasks?

**Comment by glensc** [comment]
@tomjn as you already pointed out, ci must pass, that will cover most of the code usage. then manual testing that functionality works. tests fail, because new slim is very different.

**Comment by glensc** [comment]
don't get confused this PR waits for CI to pass.

CI failing is just an indication that things are not ported to new slim structures.

**Pull request merged**
