### PR TITLE
Add an option to exclude environment variables from run view

### PR DESCRIPTION
**Pull request by ossinkine**
Sometimes environment variables contain sensitive data such as passwords and secrets, so I propose to add an option to exclude this data from run view, for example developers can have access to production profiles but have no access to secrets.

### CODE REVIEW

**Comment by Krinkle** [comment]
I think a filter feature where e.g. only a given set of keys will be shown in the interface would make sense (if there's demand for it).

However I'm a bit unsure of the currently presented use case relating to security. I think it's a mistake to allow such information to be extracted from production and sent to a profiling database, then accessed on the HTTP frontend, and even sent to Twig, only to be excluded there at the last second.

This kind of information should be excluded at the collector stage instead.

**Comment by markstory** [comment]
:+1: to what @Krinkle said. Omitting these secrets only in the twig layer is the wrong place. It would be better to omit these variables when profile runs are collected instead.

**Comment by glensc** [comment]
Hey, I started doing this in the new profiler client:
- https://github.com/perftools/php-profiler/pull/14

leave comments there wdyt or just 👍

**Comment by ossinkine** [comment]
First I wanted to filter the data at the collection stage, but then I thought that the problem was in the view but not in the collect. For example, I can create two XHGui frontend instances with different view settings for admins and developers. Or I can enable or disable the view of variables dynamically depending on various factors. If you disable this at the collection stage, then later you will not be able to see with what variables the script was executed, even if you enable the option.

**Comment by markstory** [comment]
>  If you disable this at the collection stage, then later you will not be able to see with what variables the script was executed, even if you enable the option.

This sounds like a feature to me. If you are excluding keys/secrets from collection it is generally preferable that they are not recoverable. The collector could replace them with a `<filtered>` placeholder instead of removing the value entirely.

**Comment by glensc** [comment]
with php-profiler you can modify data before sending:
- https://github.com/perftools/php-profiler#advanced-usage

```php

// stop profiler
$profiler_data = $profiler->disable();

unset($profiler_data['meta']['env']['DB_PASSWORD']);

// send $profiler_data to saver
$profiler->save($profiler_data);
```

but it's better to do that declarative way, instead of messing with internals, hence the PR:
- https://github.com/perftools/php-profiler/pull/14 (released as 0.4.0)

**Comment by ossinkine** [comment]
I don't use [perftools/php-profiler](https://github.com/perftools/php-profiler), but I use [perftools/xhgui](https://github.com/perftools/xhgui) which requires [perftools/xhgui-collector](https://github.com/perftools/xhgui-collector). So why was this issue closed? Or `xhgui-collector` does not maintained anymore and `php-profiler` should be used?

**Comment by ossinkine** [comment]
cc @glensc @markstory

**Comment by glensc** [comment]
@ossinkine perftools/xhgui is server side component, standalone from your application, on application side you install the only collector, and php-profiler is the continuation of xhgui-collector as written in it's readme. it offers new public API that should stay once it reaches 1.0.0, currently it's still using xhgui-collector internally for saver classes. and yes, you should use php-profiler in your application.

**Pull request closed without merging**
