### PR TITLE
PHP7 compatibility

### PR DESCRIPTION
**Pull request by ArabCoders**
I managed to make the app works in PHP 7 using the following changes,

added new composer package and fixed parenthesis on mongo db call

### CODE REVIEW

**Comment by markstory** [comment]
Looks like the new dependency shifts the minimum PHP version up to 5.5. Could you also update the `README` and `travis.yml` file?

**Comment by ArabCoders** [comment]
@markstory could you take look at the new requested changes?

**Comment by ArabCoders** [comment]
i also think we should go with tideways as it works cross PHP 5 and 7 instead of xhprof-beta

**Comment by markstory** [comment]
> I also think we should go with tideways as it works cross PHP 5 and 7 instead of xhprof-beta

To my knowledge tideways is already supported.

**Comment by ArabCoders** [comment]
@markstory i meant in .travis.yml it installs xhprof-beta

**Comment by markstory** [comment]
@ArabCoders Ah ok. That sounds good to me.

**Comment by ArabCoders** [comment]
@markstory i haven't really used travis alot so im not sure how to make it download and compile tideways for php

do you have any idea how to proceed?

**Comment by markstory** [comment]
The installation docs seem simple enough.

```
git clone https://github.com/tideways/php-profiler-extension.git
cd php-profiler-extension
phpize
./configure
make
make install
```

Once there is an .so for the extension, it would need to be linked into the PHP version that travis runs. I'm not entirely sure how to do that either.

**Comment by markstory** [comment]
Closing as PHP7 support was fixed in #175

**Pull request closed without merging**
