### PR TITLE
Fix perftools/php-profiler link

### PR DESCRIPTION
**Pull request by kornrunner**
Changed syntax as `[perftools/php-profiler]` alias was already defined in the file.

### CODE REVIEW

**Comment by glensc** [comment]
Pardon, but what is the problem you are trying to solve here? and I prefer markdown reflinks for readability. Describe the problem first.

**Comment by kornrunner** [comment]
Both `[perftools/php-profiler]` anchors that are rendered on Github repository page (Readme.md) actually link to `https://github.com/perftools/xhgui#profiling-a-web-request-or-cli-script` which is the value of first markdown reflink. 

It seems that Github doesn't process markdown reflink redefinition - thus second link is not linking to the repository page as one might expect (the one being changed within this PR).

**Comment by glensc** [comment]
perhaps the first link should link to the section in the readme, i.e:

```md
[bla bla bla](#profiling-a-web-request-or-cli-script)
```

**Comment by kornrunner** [comment]
Updated first link

**Pull request merged**
